apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

bases:
  - ../../resources

images:
  - name: castled/webapp
    newTag: 0.1.5-alpha
  - name: castled/app
    newTag: 0.1.5-alpha

configMapGenerator:
  - name: castled-env
    envs:
      - .env

secretGenerator:
  - name: castled-secrets
    envs:
      - .secrets
